services:
  unit:
    image: gabor:unit-916-changed
    environment:
      WP_ENVIRONMENT_TYPE: development
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp-tester
      WORDPRESS_DB_PASSWORD: supersecret
      WORDPRESS_DB_NAME: ms_subfolder
      WP_DEBUG: true
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_ALLOW_MULTISITE', true );

        /* after installing the multisite */
        define( 'MULTISITE', true );
        define( 'SUBDOMAIN_INSTALL', false );
        define( 'DOMAIN_CURRENT_SITE', 'localhost' );
        define( 'PATH_CURRENT_SITE', '/' );
        define( 'SITE_ID_CURRENT_SITE', 1 );
        define( 'BLOG_ID_CURRENT_SITE', 1 );

        define( 'WP_ENVIRONMENT_TYPE', 'local' );
    volumes:
      - ./wp:/wpms
      - ./unit.config.json:/docker-entrypoint.d/config.json
    ports:
      - "80:80"
    networks:
      - tester-ms-subfolder
  
  apache:
    image: wordpress:6.4-apache
    ports:
      - 80:80
    environment:
      WP_ENVIRONMENT_TYPE: development
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp-tester
      WORDPRESS_DB_PASSWORD: supersecret
      WORDPRESS_DB_NAME: ms_subfolder
      WP_DEBUG: true
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_ALLOW_MULTISITE', true );

        /* after installing the multisite */
        define( 'MULTISITE', true );
        define( 'SUBDOMAIN_INSTALL', false );
        define( 'DOMAIN_CURRENT_SITE', 'localhost' );
        define( 'PATH_CURRENT_SITE', '/' );
        define( 'SITE_ID_CURRENT_SITE', 1 );
        define( 'BLOG_ID_CURRENT_SITE', 1 ); 

        define( 'WP_ENVIRONMENT_TYPE', 'local' );
    volumes:
      - ./wp:/var/www/html
    networks:
      - tester-ms-subfolder

  db:
    image: mysql:8-oracle
    command: "--authentication_policy=caching_sha2_password"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "wp-tester"
      MYSQL_DATABASE: "ms_subfolder"
      MYSQL_PASSWORD: "supersecret"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - tester-ms-subfolder

networks:
  tester-ms-subfolder:
    name: tester-ms-subfolder
