services:
  unit:
    image: unit:wp-ms
    depends_on:
      - db
    env_file:
      - .docker.env
    volumes:
      - ./unit.config.json:/docker-entrypoint.d/config.json
    ports:
      - "80:80"
    networks:
      - tester-ms-subfolder
  
  apache:
    image: wordpress:6.5-php8.3-apache
    depends_on:
      - db
    ports:
      - 80:80
    env_file:
      - .docker.env
    volumes:
      - ./wp:/var/www/html
    networks:
      - tester-ms-subfolder

  nginx:
    image: nginx:1.25.5
    depends_on:
      - wp_fpm
    ports:
      - 80:80
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - tester-ms-subfolder

  wp_fpm:
    image: wordpress:6.5-php8.3-fpm-alpine
    depends_on:
      - db
    env_file:
      - .docker.env
    volumes:
      - wordpress:/var/www/html
    networks:
      - tester-ms-subfolder

  db:
    image: mysql:8-oracle
    command: "--authentication_policy=caching_sha2_password"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "wp-tester"
      MYSQL_DATABASE: "ms_subfolder"
      MYSQL_PASSWORD: "supersecret"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - tester-ms-subfolder

volumes:
  wordpress:

networks:
  tester-ms-subfolder:
    name: tester-ms-subfolder
