name: Automated API tests using Postman CLI

on: push

jobs:
  test-wp:
    runs-on: ubuntu-latest
    name: Testing WordPress
    concurrency: run-only-one
    strategy:
      matrix:
        wp_type: [ms-subfolder]
        server: [apache, nginx, unit]
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Launching WordPress ${{ matrix.wp_type }} with ${{ matrix.server }}
        run: make up-${{ matrix.wp_type }}-${{ matrix.server }}
      - name: Running postman tests
        run: make test-${{ matrix.wp_type }}